CREATE TABLE credit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        credit_code UUID NOT NULL,
        credit_value DECIMAL(19,2) NOT NULL,
        day_first_installment DATE NOT NULL,
        number_of_installments INTEGER NOT NULL,
        status int,
        customer_id BIGINT NOT NULL,
    CONSTRAINT pk_credit PRIMARY KEY (id)
);

ALTER TABLE credit ADD CONSTRAINT uc_credit_credit_code UNIQUE (credit_code);

ALTER TABLE credit ADD CONSTRAINT fk_credit_customer_id FOREIGN KEY (customer_id) REFERENCES customer (id);